import { motion } from "framer-motion";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

const faqs = [
  {
    question: "How does QuillAI generate content?",
    answer: "QuillAI uses advanced natural language processing to generate high-quality, original content. Our AI model is trained on millions of articles to understand context, tone, and SEO best practices.",
  },
  {
    question: "Is the content unique and SEO-friendly?",
    answer: "Yes! All content generated by QuillAI is unique and optimized for search engines. We include relevant keywords, meta descriptions, and proper heading structure automatically.",
  },
  {
    question: "How much time can I save with QuillAI?",
    answer: "Most users report saving 70-80% of their content creation time. What usually takes hours can be done in minutes with QuillAI.",
  },
  {
    question: "Can I customize the writing style?",
    answer: "Absolutely! QuillAI allows you to customize tone, style, and format to match your brand voice and target audience preferences.",
  },
];

export const FAQ = () => {
  return (
    <section className="py-20 px-4">
      <div className="max-w-3xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.8 }}
          className="text-center mb-16"
        >
          <h2 className="text-4xl font-bold mb-4 gradient-text">
            Frequently Asked Questions
          </h2>
          <p className="text-xl text-gray-600">
            Everything you need to know about QuillAI
          </p>
        </motion.div>
        <Accordion type="single" collapsible className="w-full">
          {faqs.map((faq, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: index * 0.1 }}
            >
              <AccordionItem value={`item-${index}`}>
                <AccordionTrigger className="text-left">
                  {faq.question}
                </AccordionTrigger>
                <AccordionContent className="text-gray-600">
                  {faq.answer}
                </AccordionContent>
              </AccordionItem>
            </motion.div>
          ))}
        </Accordion>
      </div>
    </section>
  );
};